
services:

  postgres:
    image: postgres:latest
    container_name: ktor_product_api_postgres
    ports:
      - "6000:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktor_product_api_db
    volumes:
      - postgres_data:/var/lib/data/postgresql

  ktor-product-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/ktor_product_api_db

volumes:
  postgres_data: